# Detekt config
style:
  PreferToOverPairSyntax:
    active: true
  SafeCast:
    active: true
  UnusedImports:
    active: true

naming:
  VariableMinLength:
    active: true
    minimumVariableNameLength: 2

complexity:
  NestedScopeFunctions:
    active: true
  NamedArguments:
    active: true
  StringLiteralDuplication:
    active: true

