name: spring-starter-template

services:
  db:
    image: postgres:17
    container_name: spring-database
    environment:
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: mydb
    ports:
      - 5432:5432

  redis:
    image: redis:7.2
    ports:
      - 6379:6379
    volumes:
      - ./docker/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf