name: spring-starter-template

services:
  db:
    image: postgres:17
    container_name: spring-database
    environment:
      POSTGRES_PASSWORD: supersecurepassword
      POSTGRES_DB: mydb
    ports:
      - 5432:5432

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    depends_on:
      - app

  grafana:
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    depends_on:
      - prometheus
