spring:
  application:
    name: ${SERVICE_NAME:myapplication}
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: false

springdoc:
  auto-tag-classes: false
  show-login-endpoint: true
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    displayRequestDuration: true
    defaultModelsExpandDepth: 3
    defaultModelExpandDepth: 3
    showExtensions: true
    showCommonExtensions: true
    filter: true
  packages-to-scan: com.example.web

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

myproperties:
  security:
    jwt:
      # generate with: openssl rand -base64 64
      base64-secret: lL3+Fm14g9hw2d0H6G9wjI3t65DN00ZHPE//2i0byBfjblUePaW56lJvV/ya9yDQP2MZ2In727G7BvvkpPCPpQ==
      validity-in-seconds: 3600
