spring:
  config:
    import:
      - classpath:application-infra.yml
  application:
    name: ${SERVICE_NAME:myapplication}
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:jwt/public-key.pem
          private-key-location: classpath:jwt/private-key.pem
          validity-in-seconds: 3600

springdoc:
  auto-tag-classes: false
  show-login-endpoint: true
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    displayRequestDuration: true
    defaultModelsExpandDepth: 3
    defaultModelExpandDepth: 3
    showExtensions: true
    showCommonExtensions: true
    filter: true
  packages-to-scan: com.example.web

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
