spring:
  application:
    name: ${SERVICE_NAME:myapplication}
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:jwt/public-key.pem
          private-key-location: classpath:jwt/private-key.pem
          validity-in-seconds: 3600
  datasource:
    username: sa
    password: password
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: false

springdoc:
  auto-tag-classes: false
  show-login-endpoint: true
  swagger-ui:
    operationsSorter: alpha
    tagsSorter: alpha
    displayRequestDuration: true
    defaultModelsExpandDepth: 3
    defaultModelExpandDepth: 3
    showExtensions: true
    showCommonExtensions: true
    filter: true
  packages-to-scan: com.example.web

management:
  health:
    redis:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
