spring:
  application:
    name: spring-starter-template
  output:
    ansi:
      enabled: always
  datasource:
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:supersecurepassword}
    url: jdbc:postgresql://0.0.0.0:${POSTGRES_PORT:5432}/${POSTGRES_DB:mydb}
  jpa:
    generate-ddl: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

    loggers:
      enabled: true
  info:
    git:
      enabled: true
      mode: full

example:
  security:
    jwt:
      # generate with: openssl rand -base64 64
      base64-secret: lL3+Fm14g9hw2d0H6G9wjI3t65DN00ZHPE//2i0byBfjblUePaW56lJvV/ya9yDQP2MZ2In727G7BvvkpPCPpQ==
      validity: 3600 # in seconds

