spring:
  application:
    name: ${SERVICE_NAME:spring-starter-template}
  cache:
    type: caffeine
    cache-names: 'default'
    caffeine:
      spec: 'maximumSize=500,recordStats'
  datasource:
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:supersecurepassword}
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${POSTGRES_PORT:5432}/${POSTGRES_DB:mydb}
  jpa:
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop 
    properties:
      hibernate:
        generate_statistics: false
#  mail:
#    host: ${MAIL_HOST}
#    port: 25
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}

management:
  simple:
    metrics:
      export:
        enabled: true
  endpoints:
    web:
      exposure:
        include: 'health,info,loggers,env,beans,caches,metrics,prometheus'
  endpoint:
    loggers:
      enabled: true
    health:
      show-details: always
  info:
    git:
      enabled: true

# custom application properties
example:
  application:
    base-url: https://example.com
    urls:
      activation-link: ${example.application.base-url}/api/v1/accounts/activate
      reset-password-link: ${example.application.base-url}/reset
  security:
    jwt:
      # generate with: openssl rand -base64 64
      base64-secret: lL3+Fm14g9hw2d0H6G9wjI3t65DN00ZHPE//2i0byBfjblUePaW56lJvV/ya9yDQP2MZ2In727G7BvvkpPCPpQ==
      validity-in-seconds: 86400
  authentication:
    reset-password-key-validity-in-seconds: 86400
  technical-user:
    enabled: true
    username: admin
    password: ${ADMIN_PASSWORD:supersecurepassword}

springdoc:
  auto-tag-classes: false
  show-login-endpoint: true
  swagger-ui:
    urlsPrimaryName: authentication
    operationsSorter: alpha
    tagsSorter: alpha
    displayRequestDuration: true
    defaultModelsExpandDepth: 3
    defaultModelExpandDepth: 3
    showExtensions: true
    showCommonExtensions: true
    filter: true
    urls:
      - url: oas3/admin.yaml
        name: admin
      - url: oas3/accounts.yaml
        name: accounts
      - url: oas3/authentication.yaml
        name: authentication

logging:
  level:
    root: info