spring:
  jpa:
    hibernate:
      ddl-auto: update
  web:
    resources:
      cache:
        cachecontrol:
          cache-public: true
          max-age: ${CACHE_MAX_AGE:300}
          s-max-age: ${CACHE_SMAX_AGE:3600}s # shared cache can be store for longer time than private cache
          stale-while-revalidate: ${STALE_WHILE_REVALIDATE:300} # five minutews window is enough for the shared cache to revalidate itself
