spring:
  application:
    name: spring-starter-template
  output:
    ansi:
      enabled: always
  datasource:
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:supersecurepassword}
    url: jdbc:postgresql://127.0.0.1:${POSTGRES_PORT:5432}/${POSTGRES_DB:mydb}
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop 
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  mail:
#    host: ${MAIL_HOST}
#    port: 25
#    username: ${MAIL_USERNAME}
#    password: ${MAIL_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: '*'

    loggers:
      enabled: true
  info:
    git:
      enabled: true
      mode: full

example:
  application:
    base-url: https://example.com
    urls:
      activation-link: ${example.application.base-url}/api/account/activate
      reset-password-link: ${example.application.base-url}/reset

  security:
    jwt:
      # generate with: openssl rand -base64 64
      base64-secret: lL3+Fm14g9hw2d0H6G9wjI3t65DN00ZHPE//2i0byBfjblUePaW56lJvV/ya9yDQP2MZ2In727G7BvvkpPCPpQ==
      validity-in-seconds: 86400
  authentication:
    reset-password-key-validity-in-seconds: 86400

logging:
  level:
    com.example: debug

springdoc:
  auto-tag-classes: false
  show-login-endpoint: true
