verbose: false
enumPropertyNaming: UPPERCASE
interfaceOnly: true
exceptionHandler: false
modelMutable: true
sortModelPropertiesByRequiredFlag: true
sortParamsByRequiredFlag: true
useSpringBoot3: true
useSwaggerUI: false
useTags: true
documentationProvider: none
