openapi: 3.0.4

info:
  title: Accounts API
  description: API to manage user accounts and profiles
  version: 0.0.1

servers:
  - url: /

security:
  - bearerAuth: []

tags:
  - name: accounts
    description: Accounts management operations

paths:
  /api/v1/accounts/current:
    get:
      operationId: getCurrentAccount
      summary: get authenticated account
      tags: [accounts]
      responses:
        200:
          $ref: '#/components/responses/UserInfo'
  /api/v1/accounts:
    put:
      operationId: updateUserInformation
      summary: update account info
      tags: [accounts]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  format: email
              required: [email]
      responses:
        204:
          description: user info updated successfully
  /api/v1/accounts/change-password:
    post:
      operationId: changePassword
      summary: change password
      tags: [accounts]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                currentPassword:
                  type: string
                newPassword:
                  type: string
              required: [currentPassword, newPassword]
      responses:
        204:
          description: password updated successfully

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UserInfo:
      description: user info
      content:
        application/json:
          schema:
            $ref: './admin.yaml#/components/schemas/UserInfo'